/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simplex;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import static simplex.Metodos.funcion;

/**
 *
 * @author Mors
 */
public class Agregar extends javax.swing.JFrame {

    /**
     * Creates new form Agregar
     */
    public static boolean banTipo = true;
    public static int nVar = 3;
    public static double vIndep;
    public static int signo = 1;
    private String[] options = {"≥", "=", "≤"};
    //private double var;
    private boolean minMax;
    public static String func = "";
    Metodos m = new Metodos();
    Fobjetivo Fobj = new Fobjetivo();
    public static ArrayList<Double> variables = new ArrayList<>();
    public static ArrayList<Frestriccion> restricciones = new ArrayList<>();

    public Agregar() {
        initComponents();
        btnGuardar.setVisible(false);
        btnEstandarizar.setVisible(false);
        btnAplicar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        spnNvar = new javax.swing.JSpinner();
        lblFuncion = new javax.swing.JLabel();
        rbtnMin = new javax.swing.JRadioButton();
        rbtnMax = new javax.swing.JRadioButton();
        lblNvar = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        btnReestablecer = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        rbtnRest = new javax.swing.JRadioButton();
        rbtnObj = new javax.swing.JRadioButton();
        btnEstandarizar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        btnAplicar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        spnNvar.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));
        spnNvar.setRequestFocusEnabled(false);
        spnNvar.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnNvarStateChanged(evt);
            }
        });

        lblFuncion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblFuncion.setText("Funcion");

        buttonGroup2.add(rbtnMin);
        rbtnMin.setText("Minimizar");

        buttonGroup2.add(rbtnMax);
        rbtnMax.setSelected(true);
        rbtnMax.setText("Maximizar");
        rbtnMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnMaxActionPerformed(evt);
            }
        });

        lblNvar.setText("Numero de variables:");

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnReestablecer.setText("Reestablecer");
        btnReestablecer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReestablecerActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtnRest);
        rbtnRest.setText("Restrinciones");
        rbtnRest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnRestActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtnObj);
        rbtnObj.setSelected(true);
        rbtnObj.setText("Objetivo");
        rbtnObj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnObjActionPerformed(evt);
            }
        });

        btnEstandarizar.setText("Estandarizar");
        btnEstandarizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstandarizarActionPerformed(evt);
            }
        });

        btnAplicar.setText("Aplicar");
        btnAplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAplicarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("METODO SIMPLEX");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(170, 170, 170))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(btnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 212, Short.MAX_VALUE)
                        .addComponent(btnReestablecer)
                        .addGap(117, 117, 117))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(btnEstandarizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAplicar)
                        .addGap(126, 126, 126))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator3)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(44, 44, 44)
                                        .addComponent(rbtnObj)
                                        .addGap(35, 35, 35)
                                        .addComponent(rbtnRest, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblNvar)
                                        .addGap(42, 42, 42)
                                        .addComponent(spnNvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(23, 23, 23))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rbtnMax)
                                        .addGap(10, 10, 10)
                                        .addComponent(rbtnMin, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnAceptar)
                                        .addGap(61, 61, 61)))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblFuncion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbtnObj)
                        .addComponent(rbtnRest))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNvar)
                            .addComponent(spnNvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtnMax)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbtnMin)
                        .addComponent(btnAceptar)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnReestablecer))
                .addGap(17, 17, 17)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEstandarizar)
                    .addComponent(btnAplicar))
                .addGap(63, 63, 63))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtnMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnMaxActionPerformed

    }//GEN-LAST:event_rbtnMaxActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        func = "";
        m.agregar();
        lblFuncion.setText(func);
        btnGuardar.setVisible(true);
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (banTipo) {
            if (rbtnMax.isSelected()) {
                minMax = true;
            } else {
                minMax = false;
            }
            Fobj.setMixMax(minMax);
            Fobj.setVariables(Metodos.funcion);
            Fobj.setvIndep(vIndep);
            Fobj.setTxt(func);
          
        } else {
            Frestriccion frest = new Frestriccion();
            frest.setVariables(funcion);
            frest.setnVariables(nVar - 2);
            frest.setSigno(signo);
            frest.setvIndep(vIndep);
            frest.setTxt(func);
            restricciones.add(frest);
        }
         lblFuncion.setText("");
        if (banTipo) {
            if (minMax) {
                System.out.print("Max: ");
            } else {
                System.out.print("Min: ");
            }
        }
        System.out.println(func);
       
        btnGuardar.setVisible(false);
        btnEstandarizar.setVisible(true);
    
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void spnNvarStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnNvarStateChanged
        nVar = (Integer) spnNvar.getValue() + 2;

    }//GEN-LAST:event_spnNvarStateChanged

    private void btnReestablecerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReestablecerActionPerformed
        funcion.clear();
        func = "";
        vIndep = 0;
        signo = 1;
        lblFuncion.setText("Funcion");
    }//GEN-LAST:event_btnReestablecerActionPerformed

    private void rbtnObjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnObjActionPerformed
        banTipo = true;
        rbtnMax.setVisible(true);
        rbtnMin.setVisible(true);
    }//GEN-LAST:event_rbtnObjActionPerformed

    private void rbtnRestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnRestActionPerformed
        banTipo = false;
        rbtnMax.setVisible(false);
        rbtnMin.setVisible(false);
    }//GEN-LAST:event_rbtnRestActionPerformed

    private void btnEstandarizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstandarizarActionPerformed
        System.out.println("    ESTANDARIZADO");
       // m.estandarizarFobj(Fobj);
       m.estandarizar(Fobj,restricciones);
       btnAplicar.setVisible(true);
    }//GEN-LAST:event_btnEstandarizarActionPerformed

    private void btnAplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAplicarActionPerformed
        System.out.println("            METODO SIMPLEX");
        m.resolver(Fobj, restricciones);
    }//GEN-LAST:event_btnAplicarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agregar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnAplicar;
    private javax.swing.JButton btnEstandarizar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnReestablecer;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblFuncion;
    private javax.swing.JLabel lblNvar;
    private javax.swing.JRadioButton rbtnMax;
    private javax.swing.JRadioButton rbtnMin;
    private javax.swing.JRadioButton rbtnObj;
    private javax.swing.JRadioButton rbtnRest;
    private javax.swing.JSpinner spnNvar;
    // End of variables declaration//GEN-END:variables
}
